---
version: "3"

services:
  npm:
    image: node:12.9.1-alpine
    working_dir: /opt/app
    entrypoint:
      - "/bin/sh"
      - "-c"
      - " ( [[ -L node_modules/.bin/ts-node-dev ]] || npm install ) && exec /usr/local/bin/npm \"$$@\""
    command:
      - "run"
      - "start"
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    volumes:
      - npm:/root/.npm
      - node_modules:/opt/app/node_modules
      - ./:/opt/app

volumes:
  npm:
  node_modules:
